version: '3.5'
services:

# ============================================================================
# ============================================================================
#                           AUTOTRUCK-TRUCKTRIX WEB APP
# ============================================================================
# ============================================================================

    yard_automation_app:
        image: autotruck/autotruck_webclient:2.0.4

        ports: 
            - 3080:3080            
                
        command: ["node", "express.js"]


            


           

