version: '3.5'
services:


# # ============================================================================
# # ============================================================================
    # #                       TRUCK SIMULATOR - TRUCK AND TRACTOR 
# # ============================================================================
# # ============================================================================


    agent_simulator_1:
        image: helyosframework/helyos_agent_slim_simulator:0.7.8

        volumes:
            - ./geometry_tractor.json:/app/geometry.json
            - ./aws_rbmq_ca_certificate.pem:/app/ca_certificate.pem # To verify rbmq server url.
            
        environment:

            # AGENT ID
            - UUID=Ab34069fc5-fdgs-434b-b87e-f19c5435113 
            - ASSIGNMENT_FORMAT=trajectory  # fixed | trajectory | straight_to_destination | trucktrix-path 
            - NAME=MY_TRACTOR
            - X0=-28000
            - Y0=29000
            - ORIENTATION=0.329
            - VELOCITY=1.8 
            - VEHICLE_PARTS=2
            - YARD_UID=1
            - UPDATE_RATE=10

            # RABBITMQ 
            - RBMQ_HOST=${RBMQ_HOSTNAME} 
            - RBMQ_PORT=${RBMQ_PORT}
            - ENABLE_SSL=${ENABLE_SSL} 
            - REGISTRATION_TOKEN=0001-0002-0003-0000-0004

        networks:
            - control-tower-net   



        command: ["python", "main.py"]

        deploy:
            restart_policy:
                condition: on-failure
                delay: 15s
                max_attempts: 5
                window: 60s    


    agent_simulator_2:
        image: helyosframework/helyos_agent_slim_simulator:0.7.8

        volumes:
            - ./geometry_truck.json:/app/geometry.json
            - ./aws_rbmq_ca_certificate.pem:/app/ca_certificate.pem # To verify rbmq server url.
            
        environment:

            # AGENT ID
            - UUID=Bb34069fc5-fdgs-434b-b87e-f19c5435113 
            - ASSIGNMENT_FORMAT=trajectory  # fixed | trajectory | straight_to_destination | trucktrix-path
            - NAME=MY_TRUCK
            - X0=-30000
            - Y0=10000
            - ORIENTATION=0.329
            - VELOCITY=1.8 
            - VEHICLE_PARTS=2
            - YARD_UID=1
            - UPDATE_RATE=10

            # RABBITMQ 
            - RBMQ_HOST=${RBMQ_HOSTNAME}  
            - RBMQ_PORT=${RBMQ_PORT}
            - ENABLE_SSL=${ENABLE_SSL} 
            - REGISTRATION_TOKEN=0001-0002-0003-0000-0004

        networks:
            - control-tower-net   


        command: ["python","-u", "main.py"]

        deploy:
            restart_policy:
                condition: on-failure
                delay: 15s
                max_attempts: 5
                window: 60s    


networks:
    control-tower-net:
       external: true
